version: '3'

services:
  mongo_service:
    container_name: mongo_container
    image: mongo
    volumes:
        - ./data:/data/db
    ports:
        - "27017:27017"
    networks:
      - example-net
networks:
  example-net:
    external: true